#
root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd/app"
  entrypoint = "tmp/main"
  full_bin = ""
  include_ext = ["go", "tpl", "tmpl", "html", "yaml"]
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "bin", "client", "api/proto"]
  include_dir = []
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  log = "build-errors.log"

# Poll interval (ms) when poll is enabled
  poll = false
  poll_interval = 0
 
  delay = 1000
  stop_on_error = false
  send_interrupt = true
  kill_delay = 500
  rerun = false
  rerun_delay = 500
  args_bin = []
  pre_cmd = []
  post_cmd = []

[color]
  # Customize colors
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[log]
  time = true
  main_only = false

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = true
  keep_scroll = true
